stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: blueforest/tree:1.1.4
      pushRemote: true
      registry: index.docker.io
timeout: 60
