apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "1"
    field.cattle.io/creatorId: user-rddjj
  creationTimestamp: 2018-10-27T08:44:26Z
  generation: 1
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: daemonSet-bf-tree
  name: tree
  namespace: bf
  resourceVersion: "1502397"
  selfLink: /apis/apps/v1beta2/namespaces/bf/daemonsets/tree
  uid: 82e0c9c6-d9c4-11e8-85e2-fa163e68c03b
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: daemonSet-bf-tree
  template:
    metadata:
      annotations:
        cattle.io/timestamp: 2018-10-27T08:44:24Z
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: daemonSet-bf-tree
    spec:
      containers:
      - env:
        - name: DB_HOST
          value: mongo-mongodb
        - name: DEBUG
          value: api:*
        - name: NODE_ENV
          value: production
        - name: DB_PWD
          valueFrom:
            secretKeyRef:
              key: mongodb-root-password
              name: mongo-mongodb
              optional: false
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: mongodb-root-username
              name: mongo-mongodb
              optional: false
        image: blueforest/tree:1.0.8
        imagePullPolicy: Always
        name: tree
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: blueforest
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate